#!/bin/bash
export PATH=/usr/local/Cellar/node/0.8.16/bin:/Applications/Xcode.app/Contents/Developer/usr/bin/svnlook:$PATH
REPO=$1
echo 'REPO: '$REPO >&2
TXN=$2
echo 'TXN: '$TXN >&2
lookResult=$(/usr/bin/svnlook changed $REPO --transaction $TXN)
echo 'lookup: '$lookResult >&2
file=$(/usr/bin/svnlook changed $REPO --transaction $TXN | awk '/^A|^M|^U/ {print $2;}' )
echo 'file: '$file >&2
CMD=`/usr/local/share/npm/bin/jshint --config config.json $file`
if [ $? -ne 0 ]
then
        echo $CMD >&2
        exit 1
else
	echo $CMD >&2
	exit 0
fi
